server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:8888

security:
  jwt:
    secret: yourSecretKeyForJWTTokenGenerationMustBeLongEnoughForHS256Algorithm
    expiration: 3600000
    issuer: users-service
