spring:
  application:
    name: bar-service
  cloud:
    config:
      uri: http://localhost:8888

server:
  port: 8081

jwt:
  secret: 2YrmlATq8aGvu9r5OSwV2s3g6tZqYbhyZnMNsnU/wvO27lfYxbgm5foq7F2Vsmw1eZC4WbdKHx3IXW5J7PddEA==

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
  metrics:
    enable:
      resilience4j.circuitbreaker.calls: true

resilience4j:
  circuitbreaker:
    instances:
      eventplanner-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

logging:
  level:
    root: INFO
    io.github.resilience4j: DEBUG
    org.springframework.cloud.openfeign: DEBUG


