spring:
  application:
    name: droppoint-service
  cloud:
    config:
      uri: http://localhost:8888
    function:
      definition: consumeDropPointBootstrap;consumeDropPointRemoved
    stream:
      bindings:
        consumeDropPointBootstrap-in-0:
          destination: event.drop-point.bootstrap
          group: droppoint-service
          content-type: application/json
          consumer:
            max-attempts: 3
        consumeDropPointRemoved-in-0:
          destination: event.drop-point.removed
          group: droppoint-service
          content-type: application/json
          consumer:
            max-attempts: 3
        dropPointCollectionEvent-out-0:
          destination: drop-point.collection.events
          content-type: application/json
      rabbit:
        bindings:
          consumeDropPointBootstrap-in-0:
            consumer:
              exchange-type: fanout
              auto-bind-dlq: true
          consumeDropPointRemoved-in-0:
            consumer:
              exchange-type: fanout
              auto-bind-dlq: true
          dropPointCollectionEvent-out-0:
            producer:
              exchange-type: topic
              exchange-durable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME:nextbar}
    password: ${RABBITMQ_PASSWORD:nextbar123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1

security:
  internal:
    enabled: false
    secret: ${INTERNAL_SERVICE_SECRET:}
