spring:
  application:
    name: droppoint-service
  cloud:
    config:
      uri: http://localhost:8888
    function:
      definition: consumeDropPointBootstrap;consumeDropPointCreatedEvent
    stream:
      bindings:
        consumeDropPointBootstrap-in-0:
          destination: event.drop-point.bootstrap
          group: droppoint-service
          content-type: application/json
          consumer:
            max-attempts: 3
        consumeDropPointCreatedEvent-in-0:
          destination: event.droppoint.created
          group: droppoint-service
          content-type: application/json
          consumer:
            max-attempts: 3
        dropPointCollectionEvent-out-0:
          destination: drop-point.collection.events
          content-type: application/json
      rabbit:
        bindings:
          consumeDropPointBootstrap-in-0:
            consumer:
              exchange-type: fanout
              auto-bind-dlq: true
          consumeDropPointCreatedEvent-in-0:
            consumer:
              exchange-type: fanout
              auto-bind-dlq: true
          dropPointCollectionEvent-out-0:
            producer:
              exchange-type: topic
              exchange-durable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME:nextbar}
    password: ${RABBITMQ_PASSWORD:nextbar123}
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  internal:
    enabled: false
    secret: ${INTERNAL_SERVICE_SECRET:}
