spring:
  application:
    name: warehouse-service
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      eventplanner-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        barService:
          baseConfig: default
        droppointService:
          baseConfig: default