server:
  port: 8888
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:git}
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:https://github.com/m-ali-moradi/nextBar}
          search-paths: ${SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS:config-repo}
          default-label: ${SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL:main}
          clone-on-start: ${SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START:true}
          force-pull: ${SPRING_CLOUD_CONFIG_SERVER_GIT_FORCE_PULL:true}
          username: ${SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME:${GITHUB_ACTOR:}}
          password: ${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD:${SPRING_CLOUD_CONFIG_SERVER_GIT_TOKEN:${GITHUB_TOKEN:}}}
        native:
          search-locations: ${SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS:file:../../config-repo}
          
  application:
    name: config-server

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
