server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/m-ali-moradi/Microservices_BottleDrop.git
          search-paths: config-repo
          default-label: main
          username: m-ali-moradi
          password: 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 # access token
  application:
    name: config-server

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

