# === Pull settings from Config Server ===
spring.config.import=optional:configserver:http://localhost:8888

spring.application.name=eventplanner-service
server.port=8082
# warehouse-catalogue.ribbon.listOfServers=localhost:8085


# Expose the service?s own actuator endpoints
management.endpoints.web.exposure.include=health,info

# -------------------------------------------------------------------
# H2 Database (in-memory) settings
# -------------------------------------------------------------------
spring.datasource.url=jdbc:h2:mem:eventdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Show SQL in console (helpful for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Automatically create/drop tables (for development only)
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update

# H2 Console (enabled by defaultgit )
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf template cache = false (so you can edit templates without restarting)
spring.thymeleaf.cache=false

# Circuit breaker
# feign.circuitbreaker.enabled=true
# feign.client.config.default.retryer=feign.Retryer$NeverRetry
spring.cloud.openfeign.circuitbreaker.enabled=true

# Disable Eureka registration and discovery for now
# eureka.client.register-with-eureka=false
# eureka.client.fetch-registry=false
# spring.cloud.discovery.enabled=false

# === Eureka Instance Configuration ===
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

#Debug
logging.level.io.github.resilience4j=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG


