server:
  enable-self-preservation: false
  eviction-interval-timer-in-ms: 60000
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # Prevent Eureka server from registering itself
    fetchRegistry: false # Disable fetching registry as this is the server
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    register-with-eureka: false
