spring:
  application:
    name: bar-service

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans

#logging:
#  file:
#    name: ./logs/bar-service.log
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#  level:
#    root: INFO
server:
  port: 8081
