spring.application.name=bar

spring.jpa.defer-datasource-initialization=true
spring.cloud.compatibility-verifier.enabled=false
# Enable the H2 web console
spring.h2.console.enabled=true
spring.sql.init.mode=always
# Optional: change the H2 console URL
spring.h2.console.path=/h2-console

# H2 DB URL (in-memory or file-based)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
