INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Cola', 100);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Water', 150);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Orange Juice', 75);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Lemonade', 60);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Iced Tea', 90);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Fanta', 145);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Red Bull', 155);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Sparkling Water', 120);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Apple Cider', 30);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Beer', 185);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Dr Pepper', 65);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Mountain Dew', 70);
INSERT INTO empty_bottle_stock (quantity) VALUES (0);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Grape Soda', 40);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Coconut Water', 50);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Cola Zero', 180);
INSERT INTO beverage_stock (beverage_type, quantity) VALUES ('Peach Iced Tea', 55);         